#!/usr/bin/env python3

import copy
import rospy
import arm_move
from arm_move.nodes.mover import Mover
from arm_move.srv import Step
from geometry_msgs.msg import Pose
import unittest

class ArmTest(unittest.TestCase):

    def test_reset_and_step(self):
        mover = Mover()
        mover.reset()

        step_msg = Step()
        pose_goal = Pose()
        pose_goal.orientation.w = 1.0
        pose_goal.position.x = 0.1
        pose_goal.position.y = 0
        pose_goal.position.z = 0.2
        step_msg.gripper = False
        step_msg.pose = copy.deepcopy(pose_goal)
        ret = mover.step(step_msg.pose, step_msg.gripper)
        print("ret", ret)
        self.assertTrue(ret == 1)

if __name__ == "__main__":
    # unittest.main() doesn't start roscore
    import rostest
    rostest.rosrun('arm_move', 'arm_test', ArmTest)