#!/usr/bin/env python3

"""
 The follow_rect node publishes a custom velocity message into a geometry_msgs/Twist
 and publish to the turtlebot cmd_vel in order to draw the figure eight

PUBLISHERS:
  cmd_vel (geometry_msgs/Twist) - the linear and angular velocity of the turtlebot
  path (nav_msgs/Path) - the path (x,y) of the turtlebot

SERVICES:   
  pause (Empty) - stop the turtle's motion, in a way that the trajectory can be
                    resumed
  resume (Empty) - resume the turtle's motion along the trajectory

PARAMETERS:
  width - The width of the figure eight
  height - The height of the figure eight
  period - The amount of time it takes to complete the figure eight
  ~pub_freq - The frequency at which to publish the messages (a private parameter)
"""

import rospy
import geometry_msgs.msg
from geometry_msgs.msg import Twist, Pose, Point, PoseStamped, Quaternion, Vector3
from nav_msgs.msg import Path, Odometry
from std_srvs.srv import Empty, EmptyResponse
import sympy
from sympy.abc import t
from sympy import symbols, Eq, Function, cos, sin, atan2, pi
import tf
import tf2_ros

class FollowRect():
    """ Publish a geometry_msgs/Twist of the calculated linear and angular
    velocity to the tertlebot's cmd_vel at a fixed rate 
    """
    def __init__(self):
        self.W = rospy.get_param("width")    # initializing the width of the figure eight
        self.H = rospy.get_param("height")   # initializing the height of the figure eight
        self.T = rospy.get_param("period")                # initializing the amount of time it takes to complete the
        self.R = rospy.get_param("pub_freq")              # initializing the frequency at which to publish the messages
        self.V = rospy.get_param("velocity")              # initializing the frequency at which to publish the messages
        self.odom = rospy.Subscriber("/diff/odom", Odometry, self.position_callback)
        self.pub_vel = rospy.Publisher("diff/cmd_vel", Twist, queue_size = 10)
        self.path_pub = rospy.Publisher("path", Path, queue_size = 10)

        self.rate = rospy.Rate(self.R)
        self.move_turtlebot = True
        self._t = 0
        self.init_t = rospy.get_time()
        self.round = 1
        self.x = None
        self.y = None
        self.path = Path()
        self.path.header.stamp = rospy.Time.now()
        self.path.header.frame_id = "world"
        self.path.poses = []

    def position_callback(self, data):
        """ Callback function for turtle_vel topic
        Subscribes to a topic turtle_vel, listening for TurtleVel messages. 
        The subscriber log the input as a debug level message and publishes
        a corresponding geometry_msgs/Twist on cmd_vel.
        
        Args:
          data from the subscricber
        """
        self.x = data.pose.pose.position.x
        self.y = data.pose.pose.position.y
        self.ang = data.pose.pose.orientation



    def twist_pub(self, x, omega):
        """ Create a twist suitable for the cmd_vel
        Args: None
        Returns:
            Twist - a 2D twist object corresponding to linear/angular velocity
        """
        # self.x, self.y, v, omega = 0, 0, self.V, 0
        return Twist(linear = Vector3(x = x, y = 0, z = 0),
                    angular = Vector3(x = 0, y = 0, z = omega))


    def move(self):
        """ Move the turtle by publish a twist messages to the cmd_vel
        """
        self.path.header.stamp = rospy.Time.now()
        self.path.header.frame_id = "world"
        self.path.poses.append(PoseStamped(header = self.path.header, 
                                        pose = Pose(
                                            position = Point(self.x, self.y, 0), 
                                            orientation = Quaternion(0, 0, 0, 1))))
        self.path_pub.publish(self.path)
        # rospy.logdebug(f"Posting: {self._t, self.figure_eight.get_velocity(self._t)}")
        self._t = rospy.get_time() - self.init_t
        twist = self.twist_pub(self.V, 0)
        # self.pub_turtle1_vel.publish(twist)
        self.pub_vel.publish(twist)
        rospy.logdebug(f"t = {self._t}")
        if int(self._t/self.round) == self.T:
            self.path.poses = []
            self.round += 1


    def run(self):
        while not rospy.is_shutdown():
            rospy.logdebug(f"Run Message")
            if self.move_turtlebot:
                self.move()
            else:
             rospy.logdebug(f"In pause mode")
            self.rate.sleep()


def main():
    """ The main() function. """
    rospy.init_node('follow_rect', log_level = rospy.DEBUG)
    traj = FollowRect()
    traj.run()
    rospy.spin()

if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass